#ifndef __S2_SONY_STR_DA5300ES_PROCESSOR_V1_0_H__
#define __S2_SONY_STR_DA5300ES_PROCESSOR_V1_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_PROCESS_DIG_INPUT 0
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XM_CH_INFO_REQ_DIG_INPUT 1
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUS_CH_INFO_REQ_DIG_INPUT 2


/*
* ANALOG_INPUT
*/

#define __S2_Sony_STR_DA5300ES_Processor_v1_0_COMMAND$_STRING_INPUT 0
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_COMMAND$_STRING_MAX_LEN 7
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __COMMAND$, __S2_Sony_STR_DA5300ES_Processor_v1_0_COMMAND$_STRING_MAX_LEN );

#define __S2_Sony_STR_DA5300ES_Processor_v1_0_FROM_DEVICE$_BUFFER_INPUT 1
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_FROM_DEVICE$_BUFFER_MAX_LEN 200
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __FROM_DEVICE$, __S2_Sony_STR_DA5300ES_Processor_v1_0_FROM_DEVICE$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_READY_DIG_OUTPUT 0
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_WAITING_DIG_OUTPUT 1
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUS_UPDATE_NORMAL_DIG_OUTPUT 2
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUS_UPDATE_CH_LIST_DIG_OUTPUT 3
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUS_UPDATE_SUBSCRIPTION_DIG_OUTPUT 4
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUS_UPDATE_FIRMWARE_DIG_OUTPUT 5


/*
* ANALOG_OUTPUT
*/
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_POWER_00_ANALOG_OUTPUT 0
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_POWER_01_ANALOG_OUTPUT 1
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_POWER_02_ANALOG_OUTPUT 2
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_INPUT_00_ANALOG_OUTPUT 3
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_INPUT_01_ANALOG_OUTPUT 4
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_INPUT_02_ANALOG_OUTPUT 5
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_IO_ANALOG_OUTPUT 6
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SURROUND_ANALOG_OUTPUT 7
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_BAND_ANALOG_OUTPUT 8
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_FMPRESET_NUMBER_ANALOG_OUTPUT 9
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_AMPRESET_NUMBER_ANALOG_OUTPUT 10
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMPRESET_NUMBER_ANALOG_OUTPUT 11
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSPRESET_NUMBER_ANALOG_OUTPUT 12
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_MUTE_00_ANALOG_OUTPUT 13
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_MUTE_01_ANALOG_OUTPUT 14
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_MUTE_02_ANALOG_OUTPUT 15
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMONAIR_ANALOG_OUTPUT 33
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMUPDATING_ANALOG_OUTPUT 34
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMSTRENGTH_ANALOG_OUTPUT 35
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMANTON_ANALOG_OUTPUT 36
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSOFFAIR_ANALOG_OUTPUT 37
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSUNSUB_ANALOG_OUTPUT 38
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSSTRENGTH_ANALOG_OUTPUT 39
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSANTCONN_ANALOG_OUTPUT 40
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSTUNERCONN_ANALOG_OUTPUT 41
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCHLOADING_ANALOG_OUTPUT 42
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSSSTPWR_ANALOG_OUTPUT 43
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCHLOCK_ANALOG_OUTPUT 44
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCAT_ANALOG_OUTPUT 45

#define __S2_Sony_STR_DA5300ES_Processor_v1_0_FREQ$_STRING_OUTPUT 16
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMFREQ$_STRING_OUTPUT 17
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSFREQ$_STRING_OUTPUT 18
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_FMPRESET_NAME$_STRING_OUTPUT 19
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_AMPRESET_NAME$_STRING_OUTPUT 20
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMPRESET_NAME$_STRING_OUTPUT 21
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSPRESET_NAME$_STRING_OUTPUT 22
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_TO_DEVICE$_STRING_OUTPUT 23
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCHNAME$_STRING_OUTPUT 24
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCATNAME$_STRING_OUTPUT 25
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSARTISTNAME$_STRING_OUTPUT 26
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSSONGTITLE$_STRING_OUTPUT 27
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SIRIUSCOMPOSER$_STRING_OUTPUT 28
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMCHNAME$_STRING_OUTPUT 29
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMCATNAME$_STRING_OUTPUT 30
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMARTISTNAME$_STRING_OUTPUT 31
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_XMSONGTITLE$_STRING_OUTPUT 32

#define __S2_Sony_STR_DA5300ES_Processor_v1_0_VOL_ANALOG_OUTPUT 46
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_VOL_ARRAY_LENGTH 3

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/

CREATE_INTARRAY2D( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONESTATUS, 3, 3 );;

/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_STEMP2$_STRING_MAX_LEN 7
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STEMP2$, __S2_Sony_STR_DA5300ES_Processor_v1_0_STEMP2$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SXMFREQ$_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SXMFREQ$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SXMFREQ$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SSIRIUSFREQ$_STRING_MAX_LEN 5
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SSIRIUSFREQ$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SSIRIUSFREQ$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONE$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONE$, __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONE$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_IN$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __IN$, __S2_Sony_STR_DA5300ES_Processor_v1_0_IN$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSAMP$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSAMP$, __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSAMP$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_IO_BYTE$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __IO_BYTE$, __S2_Sony_STR_DA5300ES_Processor_v1_0_IO_BYTE$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSTUNER$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSTUNER$, __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSTUNER$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSTUNER1$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSTUNER1$, __S2_Sony_STR_DA5300ES_Processor_v1_0_STATUSTUNER1$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_PRESET$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __PRESET$, __S2_Sony_STR_DA5300ES_Processor_v1_0_PRESET$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SURROUND$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SURROUND$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SURROUND$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_TEXTSTORE$_STRING_MAX_LEN 8
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __TEXTSTORE$, __S2_Sony_STR_DA5300ES_Processor_v1_0_TEXTSTORE$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_VOL$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __VOL$, __S2_Sony_STR_DA5300ES_Processor_v1_0_VOL$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_PRESETDATA$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __PRESETDATA$, __S2_Sony_STR_DA5300ES_Processor_v1_0_PRESETDATA$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SFMPRESET_NAME_TEMP$_STRING_MAX_LEN 10
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SFMPRESET_NAME_TEMP$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SFMPRESET_NAME_TEMP$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SAMPRESET_NAME_TEMP$_STRING_MAX_LEN 10
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SAMPRESET_NAME_TEMP$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SAMPRESET_NAME_TEMP$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SXMPRESET_NAME_TEMP$_STRING_MAX_LEN 10
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SXMPRESET_NAME_TEMP$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SXMPRESET_NAME_TEMP$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_SSIRIUSPRESET_NAME_TEMP$_STRING_MAX_LEN 10
CREATE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SSIRIUSPRESET_NAME_TEMP$, __S2_Sony_STR_DA5300ES_Processor_v1_0_SSIRIUSPRESET_NAME_TEMP$_STRING_MAX_LEN );
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONEVOLUME$_ARRAY_NUM_ELEMS 3
#define __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONEVOLUME$_ARRAY_NUM_CHARS 4
CREATE_STRING_ARRAY( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONEVOLUME$, __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONEVOLUME$_ARRAY_NUM_ELEMS, __S2_Sony_STR_DA5300ES_Processor_v1_0_ZONEVOLUME$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __VOL );
   unsigned short __BLEN;
   unsigned short __CSI;
   unsigned short __ACS;
   unsigned short __A;
   unsigned short __ZONE;
   unsigned short __FREQHI;
   unsigned short __FREQLO;
   unsigned short __PRESETHI;
   unsigned short __PRESETLO;
   unsigned short __VOLHI;
   unsigned short __VOLLO;
   unsigned short __SIRIUSUPDATEBIT5;
   unsigned short __SIRIUSUPDATEBIT4;
   DECLARE_INTARRAY( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONESTATUS );
   unsigned long __VOLUME;
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STEMP2$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SXMFREQ$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SSIRIUSFREQ$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONE$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __IN$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSAMP$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __IO_BYTE$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSTUNER$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __STATUSTUNER1$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __PRESET$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SURROUND$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __TEXTSTORE$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __VOL$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __PRESETDATA$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SFMPRESET_NAME_TEMP$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SAMPRESET_NAME_TEMP$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SXMPRESET_NAME_TEMP$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __SSIRIUSPRESET_NAME_TEMP$ );
   DECLARE_STRING_ARRAY( S2_Sony_STR_DA5300ES_Processor_v1_0, __ZONEVOLUME$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __COMMAND$ );
   DECLARE_STRING_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0, __FROM_DEVICE$ );
};

START_NVRAM_VAR_STRUCT( S2_Sony_STR_DA5300ES_Processor_v1_0 )
{
};



#endif //__S2_SONY_STR_DA5300ES_PROCESSOR_V1_0_H__

